language: java
sudo: true
jdk:
  - oraclejdk8

branches:
  only:
  - master

before_install:
  - "sudo apt-get install graphviz"
  - "which dot"

after_success:
  - mvn clean cobertura:cobertura coveralls:report
